{
 "title": "Flux CD Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Helm Release Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "flux_helm_operator_release_queue_length_count",
     "legendFormat": "Release Queue"
    }
   ]
  },
  {
   "title": "Flux Sync",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(flux_daemon_sync_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "flux sync duration"
    }
   ]
  },
  {
   "title": "Helm Operator Sync",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flux_helm_operator_release_phase_duration_seconds_bucket[1m])) by (action, le))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Flux CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "CPU seconds / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"fluxcd\",pod_name=~\"flux.*\", container_name!~\"POD|istio-proxy\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Helm Operator CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "CPU seconds / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"fluxcd\",pod_name=~\"helm-operator.*\", container_name!~\"POD|istio-proxy\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Flux Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"fluxcd\",pod_name=~\"flux.*\", container_name!~\"POD|istio-proxy\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_namespace=\"fluxcd\", kubernetes_pod_name=~\"flux.*\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_namespace=\"fluxcd\", kubernetes_pod_name=~\"flux.*\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{kubernetes_namespace=\"fluxcd\", kubernetes_pod_name=~\"flux.*\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=\"fluxcd\", kubernetes_pod_name=~\"flux.*\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Helm Operator Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"fluxcd\",pod_name=~\"helm-operator.*\", container_name!~\"POD|istio-proxy\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "go_memstats_alloc_bytes{release=\"helm-operator\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{release=\"helm-operator\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{release=\"helm-operator\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{release=\"helm-operator\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Flux Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"fluxcd\",pod_name=~\"flux.*\"}[1m])) ",
     "legendFormat": "received"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{namespace=\"fluxcd\",pod_name=~\"flux.*\"}[1m]))",
     "legendFormat": "transmited"
    }
   ]
  },
  {
   "title": "Helm Operator  Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"fluxcd\",pod_name=~\"helm-operator.*\"}[1m])) ",
     "legendFormat": "received"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{namespace=\"fluxcd\",pod_name=~\"helm-operator.*\"}[1m]))",
     "legendFormat": "transmited"
    }
   ]
  },
  {
   "title": "Flagger CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "CPU seconds / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"fluxcd\",pod_name=~\"flagger-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)\", container_name!~\"POD|istio-proxy\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Flagger Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"fluxcd\", pod_name=~\"flagger-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)\", container_name!~\"POD|istio-proxy\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{kubernetes_namespace=\"fluxcd\", kubernetes_pod_name=~\"flagger-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}} bytes allocated"
    },
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{kubernetes_namespace=\"fluxcd\", kubernetes_pod_name=~\"flagger-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name}} alloc rate"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{kubernetes_namespace=\"fluxcd\", kubernetes_pod_name=~\"flagger-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name}} stack inuse"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{kubernetes_namespace=\"fluxcd\", kubernetes_pod_name=~\"flagger-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name}} heap inuse"
    }
   ]
  }
 ]
}